"""squish/disagg_prefill.py

DisaggPrefillNode / DisaggDecodeNode — Disaggregated prefill and decode for
high-throughput LLM serving.

In a standard inference server the same GPU processes both the compute-heavy
prefill phase (processing the full prompt in a single forward pass) and the
memory-bandwidth-bound decode phase (generating one token at a time).
Because these two workloads have fundamentally different arithmetic
intensities, mixing them on the same device leads to GPU under-utilisation in
both directions.

Disaggregated prefill solves this by dedicating separate machine types:

1. **Prefill node** — receives raw token IDs, builds the full KV cache for all
   layers in a single pass, generates the first output token, serialises the
   KV state, and sends it to the decode node.
2. **Decode node** — receives the KV payload, installs it, then autoregressively
   generates subsequent tokens using the cached context.

This module simulates the communication and state management at the system
level.  Actual GPU kernels and network transfers are replaced with NumPy
random-number generation and in-memory byte buffers.

KV serialisation format (little-endian binary)::

    [ n_layers  : int32 ]
    [ n_heads   : int32 ]
    [ seq_len   : int32 ]
    [ head_dim  : int32 ]
    for each layer:
        [ keys   : float32 * n_heads * seq_len * head_dim ]
        [ values : float32 * n_heads * seq_len * head_dim ]

Reference:
    Zhong et al., "DistServe: Disaggregating Prefill and Decoding for
    Goodput-optimized Large Language Model Serving", OSDI 2024.
    https://arxiv.org/abs/2401.09670

Example usage::

    import numpy as np
    from squish.disagg_prefill import (
        DisaggConfig, DisaggPrefillNode, DisaggDecodeNode
    )

    cfg     = DisaggConfig(n_heads=8, head_dim=64, n_layers=4)
    prefill = DisaggPrefillNode(cfg)
    decode  = DisaggDecodeNode(cfg)

    token_ids = np.arange(32, dtype=np.int32)
    payload   = prefill.prefill("seq-1", token_ids)
    decode.load_payload(payload)

    for _ in range(5):
        tok = decode.step("seq-1")
        print(f"generated token: {tok}")
"""

from __future__ import annotations

__all__ = [
    "DisaggConfig",
    "PrefillPayload",
    "DisaggPrefillNode",
    "DisaggDecodeNode",
]

import dataclasses
import struct
from typing import Optional

import numpy as np


# Binary header for multi-layer KV payloads: four int32 fields.
_KV_HEADER_FORMAT: str = "<4i"
_KV_HEADER_SIZE:   int = struct.calcsize(_KV_HEADER_FORMAT)  # 16 bytes

# Simulated vocabulary size (GPT-2 tokeniser range).
_VOCAB_SIZE: int = 50257


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------


@dataclasses.dataclass
class DisaggConfig:
    """Configuration shared by both prefill and decode nodes.

    Attributes:
        n_heads:  Number of attention heads per transformer layer.
        head_dim: Dimension of each attention head.
        n_layers: Number of transformer layers in the model.
    """

    n_heads:  int
    head_dim: int
    n_layers: int

    def __post_init__(self) -> None:
        if self.n_heads < 1:
            raise ValueError(f"n_heads must be >= 1, got {self.n_heads}")
        if self.head_dim < 1:
            raise ValueError(f"head_dim must be >= 1, got {self.head_dim}")
        if self.n_layers < 1:
            raise ValueError(f"n_layers must be >= 1, got {self.n_layers}")


# ---------------------------------------------------------------------------
# Payload
# ---------------------------------------------------------------------------


@dataclasses.dataclass
class PrefillPayload:
    """KV payload transferred from the prefill node to the decode node.

    Attributes:
        seq_id:      Unique identifier for the in-flight sequence.
        n_tokens:    Number of prompt tokens (depth of the KV cache).
        kv_data:     Serialised KV tensors for all layers (see module docstring
                     for the binary format).
        first_token: First auto-regressive token generated by the prefill node.
    """

    seq_id:      str
    n_tokens:    int
    kv_data:     bytes
    first_token: int


# ---------------------------------------------------------------------------
# Internal serialisation helpers
# ---------------------------------------------------------------------------


def _pack_kv_layers(
    n_layers: int,
    n_heads:  int,
    head_dim: int,
    keys_by_layer:   list[np.ndarray],
    values_by_layer: list[np.ndarray],
) -> bytes:
    """Serialise per-layer KV tensors into a single byte buffer.

    Args:
        n_layers:        Number of transformer layers.
        n_heads:         Number of attention heads.
        head_dim:        Dimension per head.
        keys_by_layer:   List of ``n_layers`` key arrays, each
                         ``(n_heads, seq_len, head_dim)`` float32.
        values_by_layer: Matching list of value arrays.

    Returns:
        Binary payload beginning with a 16-byte header followed by
        interleaved keys/values for every layer.
    """
    seq_len = keys_by_layer[0].shape[1]
    header  = struct.pack(_KV_HEADER_FORMAT, n_layers, n_heads, seq_len, head_dim)
    parts: list[bytes] = [header]
    for k, v in zip(keys_by_layer, values_by_layer):
        parts.append(k.astype(np.float32).tobytes())
        parts.append(v.astype(np.float32).tobytes())
    return b"".join(parts)


def _unpack_kv_layers(
    data: bytes,
) -> tuple[int, int, int, int, list[np.ndarray], list[np.ndarray]]:
    """Deserialise a byte buffer produced by :func:`_pack_kv_layers`.

    Returns:
        Tuple ``(n_layers, n_heads, seq_len, head_dim,
        keys_list, values_list)``.

    Raises:
        ValueError: If the buffer is too short to satisfy the declared header
                    dimensions.
    """
    if len(data) < _KV_HEADER_SIZE:
        raise ValueError(
            f"KV payload too short for header: "
            f"need {_KV_HEADER_SIZE} bytes, got {len(data)}"
        )
    n_layers, n_heads, seq_len, head_dim = struct.unpack(
        _KV_HEADER_FORMAT, data[:_KV_HEADER_SIZE]
    )

    n_elements   = n_heads * seq_len * head_dim
    tensor_bytes = n_elements * np.dtype(np.float32).itemsize

    expected_size = _KV_HEADER_SIZE + 2 * n_layers * tensor_bytes
    if len(data) < expected_size:
        raise ValueError(
            f"KV payload too short: expected {expected_size} bytes, "
            f"got {len(data)}"
        )

    offset = _KV_HEADER_SIZE
    keys_list:   list[np.ndarray] = []
    values_list: list[np.ndarray] = []

    for _ in range(n_layers):
        k = np.frombuffer(data[offset:offset + tensor_bytes], dtype=np.float32)
        keys_list.append(k.reshape(n_heads, seq_len, head_dim).copy())
        offset += tensor_bytes

        v = np.frombuffer(data[offset:offset + tensor_bytes], dtype=np.float32)
        values_list.append(v.reshape(n_heads, seq_len, head_dim).copy())
        offset += tensor_bytes

    return n_layers, n_heads, seq_len, head_dim, keys_list, values_list


# ---------------------------------------------------------------------------
# Prefill node
# ---------------------------------------------------------------------------


class DisaggPrefillNode:
    """Simulates the prefill-side node in a disaggregated serving system.

    On each :meth:`prefill` call the node:

    1. Generates synthetic KV tensors for every layer using a seeded RNG
       (simulating a forward pass over the prompt tokens).
    2. Derives the first output token from a deterministic function of the
       last layer's key norms, clipped to the vocabulary range.
    3. Serialises the KV state for transfer to the decode node.

    Args:
        config: A :class:`DisaggConfig` instance.
    """

    def __init__(self, config: DisaggConfig) -> None:
        self._cfg = config
        self._rng = np.random.default_rng(0)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def prefill(self, seq_id: str, token_ids: np.ndarray) -> PrefillPayload:
        """Process a prompt and produce a :class:`PrefillPayload`.

        Args:
            seq_id:    Unique sequence identifier string.
            token_ids: 1-D int32 array of prompt token IDs.  Must be non-empty.

        Returns:
            A :class:`PrefillPayload` ready to be handed to
            :meth:`DisaggDecodeNode.load_payload`.

        Raises:
            ValueError: If ``token_ids`` is not 1-D or is empty.
        """
        token_ids = np.asarray(token_ids, dtype=np.int32)
        if token_ids.ndim != 1:
            raise ValueError(
                f"token_ids must be 1-D, got shape {token_ids.shape}"
            )
        if token_ids.size == 0:
            raise ValueError("token_ids must not be empty")

        n_tokens = int(token_ids.size)
        kv_shape = (self._cfg.n_heads, n_tokens, self._cfg.head_dim)

        keys_by_layer:   list[np.ndarray] = []
        values_by_layer: list[np.ndarray] = []

        for _ in range(self._cfg.n_layers):
            keys_by_layer.append(
                self._rng.standard_normal(kv_shape).astype(np.float32)
            )
            values_by_layer.append(
                self._rng.standard_normal(kv_shape).astype(np.float32)
            )

        kv_data = _pack_kv_layers(
            self._cfg.n_layers,
            self._cfg.n_heads,
            self._cfg.head_dim,
            keys_by_layer,
            values_by_layer,
        )

        # Derive first token: argmax of mean key norms over the last layer,
        # wrapped into the vocabulary range.
        last_key_norms = np.linalg.norm(keys_by_layer[-1], axis=-1).mean(axis=0)
        first_token    = int(np.argmax(last_key_norms) % _VOCAB_SIZE)

        return PrefillPayload(
            seq_id=seq_id,
            n_tokens=n_tokens,
            kv_data=kv_data,
            first_token=first_token,
        )


# ---------------------------------------------------------------------------
# Decode node
# ---------------------------------------------------------------------------

# Arbitrary large prime multiplier for the LCG-style next-token derivation.
_LCG_MULTIPLIER: int = 6364136223846793005


class DisaggDecodeNode:
    """Simulates the decode-side node in a disaggregated serving system.

    Receives :class:`PrefillPayload` objects from a :class:`DisaggPrefillNode`,
    installs their KV caches, and autoregressively generates tokens.
    Token generation is simulated with a deterministic mapping keyed on the
    previous token and the step count; no actual model weights are involved.

    Args:
        config: A :class:`DisaggConfig` instance.
    """

    def __init__(self, config: DisaggConfig) -> None:
        self._cfg = config
        # seq_id → {n_tokens, step, last_token, keys, values}
        self._loaded: dict[str, dict] = {}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def load_payload(self, payload: PrefillPayload) -> None:
        """Install a KV payload received from the prefill node.

        Args:
            payload: :class:`PrefillPayload` produced by
                     :meth:`DisaggPrefillNode.prefill`.

        Raises:
            ValueError: If ``payload.seq_id`` is already loaded on this node.
        """
        if payload.seq_id in self._loaded:
            raise ValueError(
                f"Sequence '{payload.seq_id}' is already loaded; "
                "call step() to consume tokens or remove it before reloading."
            )

        _, _, _, _, keys_list, values_list = _unpack_kv_layers(payload.kv_data)

        self._loaded[payload.seq_id] = {
            "n_tokens":   payload.n_tokens,
            "step":       0,
            "last_token": payload.first_token,
            "keys":       keys_list,
            "values":     values_list,
        }

    def step(self, seq_id: str) -> int:
        """Generate the next token for the specified sequence.

        Args:
            seq_id: Identifier of the loaded sequence.

        Returns:
            Next generated token ID, an integer in ``[0, 50256]``.

        Raises:
            KeyError: If ``seq_id`` has not been loaded via
                      :meth:`load_payload`.
        """
        if seq_id not in self._loaded:
            raise KeyError(
                f"Sequence '{seq_id}' is not loaded on this decode node. "
                "Call load_payload() first."
            )

        state = self._loaded[seq_id]

        # Deterministic pseudo-random next token derived from last token and
        # step count using a simple linear-congruential mixing step.
        mixed      = state["last_token"] ^ (state["step"] * _LCG_MULTIPLIER)
        next_token = int(abs(mixed) % _VOCAB_SIZE)

        state["step"]       += 1
        state["last_token"]  = next_token

        return next_token

    def is_loaded(self, seq_id: str) -> bool:
        """Return ``True`` if ``seq_id`` has an active KV cache on this node.

        Args:
            seq_id: Sequence identifier to query.
        """
        return seq_id in self._loaded
